#!/usr/bin/env python3
"""
Fig 10a -- one camera view per social-DANNCE dataset family, with the sDANNCE 3D
poses reprojected through the deposit's own calibration and colored by animal
identity (the app's screen palette, print-unsafe deliberately: the dots sit ON
the photograph and must match what the app would draw).

WHY THIS PANEL LEADS THE FIGURE. Everything downstream of it depends on one
claim: that our reading of the deposit's MATLAB calibration (K stored
transposed, 1-based principal point, row-vector x = X.R + t, RDistort/TDistort)
is correct. The quantitative version is in 10b and in
figs/fig10-bench/validate_*.json (reprojection matches Label3D's own stored 2D
to ~1e-13 px on every camera of all 41 sessions); this panel is the same fact
at a glance -- the skeletons land on the animals, in three different arenas,
including the bedding arena whose floor is deformable and the triad arena with
a third animal.

Tiles (full-resolution single-camera frames, generated by
figs/fig10-bench/fig10_tiles.py from the deposit's videos):
  TRIADS   2023_03_01_M1_M2_M3, Camera2, frame 30000  (3 rats, CHD8 males)
  BEDDING  2024_05_05_F1_F2,   Camera1, frame 5000    (2 females, bedding)
  SCN2A    2022_10_04_M1_M2,   Camera4, frame 31267   (dyad, upright + crouched;
           re-picked from an 8-candidate sheet, results/agg/scn2a_tile_candidates.jpg)

Identical crop on every tile (image_row enforces it): the arena fills the tile,
the surround is trimmed.

Source images: figs/fig10-bench/results/agg/tile_{triads,bedding,scn2a}.png

Skeleton upgrade (Eric 2026-08-16): tiles now render full skeletons — the
deposit's own joints_idx edges + translucent convex-hull body panels + joint
dots — instead of bare keypoint dots (see fig10_tiles.py EDGES/SURFACES).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.style import use, image_row, save

use()

AGG = Path(__file__).resolve().parent.parent / "fig10-bench" / "results" / "agg"

fig, _ = image_row(
    [AGG / "tile_triads.png", AGG / "tile_bedding.png", AGG / "tile_scn2a.png"],
    # Middle-dot separators, the set's own tile-caption idiom (fig6b's
    # "difficulty 4 · 4 animals ·..."; fig10f's subplot titles) -- the ASCII "--"
    # here was the one caption in the set typeset with a double hyphen.
    labels=["TRIADS · 3 rats", "BEDDING · 2 rats", "SCN2A · 2 rats"],
    span="full",
    crop=(0.10, 0.12, 0.90, 0.97),
)
save(fig, 10, "a", "views")
